# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
devPort = 4321
baseUrl = "https://clint-jordan.github.io/dark-matter"

[_.globalMeta]
title = "dark-matter"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "John Doe Blog"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "dark-matter"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.notesMeta]
title = "dark-matter"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.Meta]
title = "dark-matter"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.searchMeta]
title = "dark-matter"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "/card-image.webp"

[_.hero]
title = "John Doe"
subtitle = "A profound defining statement"
image = "/card-image.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "John Doe"
githubProfile = "https://github.com/clint-jordan"
twitterProfile = "https://twitter.com"
linkedinProfile = "https://linkedin.com/"

[_.texts]
blogName = "Blog"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
notes = "/notes"
search = "/search"