# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
devPort = 4321
baseUrl = "https://clint-jordan.github.io/dark-matter"

[_.globalMeta]
title = "clint-jordan"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "clint-jordan"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "clint-jordan"
description = ""
longDescription = ""
cardImage = "/card-image.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "/card-image.webp"

[_.hero]
title = "Clint Jordan"
subtitle = "A profound defining statement"
image = "/card-image.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "clint-jordan"
githubProfile = "https://github.com/clint-jordan"
twitterProfile = "https://twitter.com"
linkedinProfile = "https://linkedin.com/"

[_.texts]
articlesName = "Blog"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"